project:
  type: website
  output-dir: ../_site/pt-br

lang: pt-BR

website:
  title: "Sistemas Embarcados"
  navbar:
    background: primary
    right:
      - text: "ðŸ‡ºðŸ‡¸ English"
        href: ../en/index.html
  sidebar:
    style: "floating"
    contents:
      - href: index.qmd
        text: "InÃ­cio"
      - section: "Semana 01: GPIO"
        contents:
          - semana-01/teoria.qmd
          - semana-01/lab.qmd
      # Adicione as demais semanas seguindo este padrÃ£o

format:
  html:
    theme: cosmo
    css: ../styles.css
    toc: true
    number-sections: true
